# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Pref.create!(pref_name: "北海道")
Pref.create!(pref_name: "青森県")
Pref.create!(pref_name: "岩手県")
Pref.create!(pref_name: "宮城県")
Pref.create!(pref_name: "秋田県")
Pref.create!(pref_name: "山形県")
Pref.create!(pref_name: "福島県")
Pref.create!(pref_name: "茨城県")
Pref.create!(pref_name: "栃木県")
Pref.create!(pref_name: "群馬県")
Pref.create!(pref_name: "埼玉県")
Pref.create!(pref_name: "千葉県")
Pref.create!(pref_name: "東京都")
Pref.create!(pref_name: "神奈川県")
Pref.create!(pref_name: "新潟県")
Pref.create!(pref_name: "富山県")
Pref.create!(pref_name: "石川県")
Pref.create!(pref_name: "福井県")
Pref.create!(pref_name: "山梨県")
Pref.create!(pref_name: "長野県")
Pref.create!(pref_name: "岐阜県")
Pref.create!(pref_name: "静岡県")
Pref.create!(pref_name: "愛知県")
Pref.create!(pref_name: "三重県")
Pref.create!(pref_name: "滋賀県")
Pref.create!(pref_name: "京都府")
Pref.create!(pref_name: "大阪府")
Pref.create!(pref_name: "兵庫県")
Pref.create!(pref_name: "奈良県")
Pref.create!(pref_name: "和歌山県")
Pref.create!(pref_name: "鳥取県")
Pref.create!(pref_name: "島根県")
Pref.create!(pref_name: "岡山県")
Pref.create!(pref_name: "広島県")
Pref.create!(pref_name: "山口県")
Pref.create!(pref_name: "徳島県")
Pref.create!(pref_name: "香川県")
Pref.create!(pref_name: "愛媛県")
Pref.create!(pref_name: "高知県")
Pref.create!(pref_name: "福岡県")
Pref.create!(pref_name: "佐賀県")
Pref.create!(pref_name: "長崎県")
Pref.create!(pref_name: "熊本県")
Pref.create!(pref_name: "大分県")
Pref.create!(pref_name: "宮崎県")
Pref.create!(pref_name: "鹿児島県")
Pref.create!(pref_name: "沖縄県")

Zone.create!(zone_name: "1区")
Zone.create!(zone_name: "2区")
Zone.create!(zone_name: "3区")
Zone.create!(zone_name: "4区")
Zone.create!(zone_name: "5区")
Zone.create!(zone_name: "6区")
Zone.create!(zone_name: "7区")
Zone.create!(zone_name: "8区")
Zone.create!(zone_name: "9区")
Zone.create!(zone_name: "10区")
Zone.create!(zone_name: "11区")
Zone.create!(zone_name: "12区")
Zone.create!(zone_name: "13区")
Zone.create!(zone_name: "14区")
Zone.create!(zone_name: "15区")
